apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    circleci.com/project-slug: github/dhanu0001/backstage-demo
    github.com/project-slug: dhanu0001/backstage-demo
    datadoghq.com/dashboard-url: https://p.datadoghq.com/sb/dcafc21c-4ee4-11ec-a604-da7ad0900002-40c4a7dd244bf26002b6b8f2d3591d0a
 #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:dhanu0001
  lifecycle: experimental
