version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecs: circleci/aws-ecs@3.2
jobs:
  deploy-scheduled-task:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - aws-cli/setup:
          aws-region: AWS_REGION
          profile-name: OIDC-PROFILE
          role-arn: 'arn:aws:iam::123456789012:role/OIDC_ARN'
          role-session-name: example-session-name
          # session-duration: 3600
      - aws-ecs/update-task-definition-from-json:
          task-definition-json: my-app-definition.json
      - aws-ecs/deploy-ecs-scheduled-task:
          rule-name: example-rule
workflows:
  deploy:
    jobs:
      - deploy-scheduled-task:
          context:
            - backstage-integration