version: 2.1
jobs:
  build-modules:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
            root: .
            paths:
              - node_modules
  unit-test:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/file
    steps:
      - checkout
      - attach_workspace:
          at: .
#      - run: npm test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: backstage:latest
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          digest-path: /tmp/digest.txt
          image: backstage:latest
          tag: "latest,$CIRCLE_SHA1"
      - run:
          command: |
            echo "Digest is: ${</tmp/digest.txt}"
            echo "testing!!!"
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
         name: install dependencies
         command: |
            pip install ecs-deploy
      - run:
          name: deploy
          command: |
            ecs deploy $ECS CLUSTER NAME $ECS SERVICE  --image website-service anju001/backstage:latest:$CIRCLE SHA1 --timeout 1200 --ignore-warnings --region $AWS REGION
orbs:
  docker: circleci/docker@1.4.0

workflows:
  version: 2
  test:
    jobs:
      - build-modules
      - unit-test:
          requires:
            - build-modules
      - build-and-push:
          filters:
            branches:
              only: master
          requires:
            - unit-test
      - deploy:
          requires:
            - build-and-push 
